### ISSUE TITLE
"Size of backlog" is wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#13]
If I show a chart only over the last two years, the current value is around 500 but if I configure the chart to look over the past 5 years then it show around 1000 tickets. This has to be wrong, it should always display the same amount of ticket with the status open at a certain date.

**Comment by florentk** [comment]
Yes, this is a problem, such as having a negative size (eg last 6 months). To obtain the curve I deduct the cumulated sum of closed tickets from the cumulated sum of open tickets, which should give the number of tickets opened on a certain date. But this sum is calculated from the start of the viewing period (2018 if the period is two years) and not from the date of the first data. Hence the problem. So the evolution is correct but not the value.
I don't know how to do otherwise at the moment, because I don't directly have the value "number of tickets open" on a given date. Perhaps it will have to be calculated outside of Kibana, during data collection.

**Comment by florentk** [comment]
@kelson42 I looking for use Studies in GrimoireELK to create specifics indices because I can't get the evolution of "number of opened issues" in ElasticSearch database to create the required graph.

**Comment by florentk** [comment]
done via bfa2632 and https://github.com/florentk/grimoirelab-elk/commit/932bdcf4460c657a87f05e08b00ea83f23eb6095 and https://github.com/florentk/grimoirelab-sirmordred/commit/10a6ec1c3b4ccac64cfae115555942b1f653d17a
