### ISSUE TITLE
"Size of backlog" numbers are wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#25]
A simple manual verification shows that numbers are understimated

**Comment by florentk** [comment]
@kelson42 Indeed ! I had tested on two or three repository but I did not see the problem because the bug is with many opened issues (like libzim or kiwix-android). I have found the bug, this is due to a misunderstanding of Elastic Search (is new for me !), I had not seen that he returned a maximum of ten results if a max is not provided ...

**Comment by florentk** [comment]
fixed via 43f3343f711d56dd74de3aa7025cc3c5f59d6a58
